wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://packages.applied-caas-gateway1.internal.api.openai.org/artifactory/maven-public/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
